[*] Running ...
Traceback (most recent call last):
  File "E:\Coding\pythonProject\llm4contract\problems\eval.py", line 136, in <module>
    _p, _c, _v, _contract_logs = extract_data(_dataset_path)
  File "E:\Coding\pythonProject\llm4contract\problems\eval.py", line 108, in extract_data
    with open(dataset_path, "rb", encoding='utf-8') as f:
ValueError: binary mode doesn't take an encoding argument
