[*] Running ...
[*] Dataset loaded: E:\Coding\pythonProject\llm4contract\problems\dataset\train_01.pkl with 5 instances.
→ Best principal utility: 4.03773573646638
→ Best action index:    98
→ Best contract w:       [0.94877393 0.         0.         4.06570984 4.98148626]
Traceback (most recent call last):
  File "E:\Coding\pythonProject\llm4contract\problems\eval.py", line 150, in <module>
    obj = evaluate_llm((_p, _c, _v, _contract_logs))
  File "E:\Coding\pythonProject\llm4contract\problems\eval.py", line 101, in evaluate_llm
    inferred_agent_setting = llm_agent_solver(v, content)
  File "E:\Coding\pythonProject\llm4contract\problems\gpt.py", line 52, in agent_solver_v2
    def cluster_and_get_centroids(n_clusters: int) -> np.ndarray:
TypeError: AgglomerativeClustering.__init__() got an unexpected keyword argument 'affinity'
