[*] Running ...
[*] Dataset loaded: E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\dataset\train_01.pkl with 3 instances.
→ Best principal utility: 0.0006193891649213826
→ The corresponding best action is: 6
→ The corresponding agent utility is: 1.000007097528427e-16
Traceback (most recent call last):
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\eval.py", line 170, in <module>
    obj, _ = evaluate_llm((_p, _c, _v, _contract_logs))
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\eval.py", line 105, in evaluate_llm
    inferred_agent_setting = llm_agent_solver(v, content)
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\gpt.py", line 46, in agent_solver_v2
    gmm_models.append(gmm)
  File "D:\Software\anaconda3\envs\llm4contract\lib\site-packages\sklearn\mixture\_base.py", line 180, in fit
    self.fit_predict(X, y)
  File "D:\Software\anaconda3\envs\llm4contract\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "D:\Software\anaconda3\envs\llm4contract\lib\site-packages\sklearn\mixture\_base.py", line 211, in fit_predict
    X = validate_data(self, X, dtype=[np.float64, np.float32], ensure_min_samples=2)
  File "D:\Software\anaconda3\envs\llm4contract\lib\site-packages\sklearn\utils\validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
  File "D:\Software\anaconda3\envs\llm4contract\lib\site-packages\sklearn\utils\validation.py", line 1130, in check_array
    raise ValueError(
ValueError: Found array with 1 sample(s) (shape=(1, 12)) while a minimum of 2 is required by GaussianMixture.
